* musinsa : 원본 데이터 
* data1 : c_number(int -> object) 진행했다가 다시 복원함 : musinsa랑 동일
    * c_number를  object type으로 변환 시, 딕셔너리 key('c_number')를 통해 value('c_name') 추출할 때 문자열로 취급해야하므로 복원
* data2 : 수정 데이터 
* data3 : c_number, c_name 중복 제거
* result_dict : c_number와 c_name & link 매핑

In [49]:
import pandas as pd
musinsa = pd.read_csv("./musinsa_data.csv")

In [50]:
musinsa.head()

,temp,c_number,c_name,gender,height(cm),weight(kg),fit,link,size,c_result
0,28,0,레이어드 슬리브리스 탑_일반 기장 [화이트],남자,173,65,적당함,//image.msscdn.net/images/goods_img/20210825/2...,M,M0
1,28,0,레이어드 슬리브리스 탑_일반 기장 [화이트],남자,184,80,적당함,//image.msscdn.net/images/goods_img/20210825/2...,L,L0
2,28,0,레이어드 슬리브리스 탑_일반 기장 [화이트],남자,172,63,적당함,//image.msscdn.net/images/goods_img/20210825/2...,S,S0
3,28,0,레이어드 슬리브리스 탑_일반 기장 [화이트],남자,182,78,적당함,//image.msscdn.net/images/goods_img/20210825/2...,L,L0
4,28,0,레이어드 슬리브리스 탑_일반 기장 [화이트],남자,173,71,적당함,//image.msscdn.net/images/goods_img/20210825/2...,M,M0

In [51]:
musinsa.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6150 entries, 0 to 6149
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   temp        6150 non-null   int64
 1   c_number    6150 non-null   int64
 2   c_name      6150 non-null   object
 3   gender      6150 non-null   object
 4   height(cm)  6150 non-null   int64
 5   weight(kg)  6150 non-null   int64
 6   fit         6150 non-null   object
 7   link        6150 non-null   object
 8   size        6150 non-null   object
 9   c_result    6150 non-null   object
dtypes: int64(4), object(6)
memory usage: 480.6+ KB

In [52]:
data1 = musinsa
data1

,temp,c_number,c_name,gender,height(cm),weight(kg),fit,link,size,c_result
0,28,0,레이어드 슬리브리스 탑_일반 기장 [화이트],남자,173,65,적당함,//image.msscdn.net/images/goods_img/20210825/2...,M,M0
1,28,0,레이어드 슬리브리스 탑_일반 기장 [화이트],남자,184,80,적당함,//image.msscdn.net/images/goods_img/20210825/2...,L,L0
2,28,0,레이어드 슬리브리스 탑_일반 기장 [화이트],남자,172,63,적당함,//image.msscdn.net/images/goods_img/20210825/2...,S,S0
3,28,0,레이어드 슬리브리스 탑_일반 기장 [화이트],남자,182,78,적당함,//image.msscdn.net/images/goods_img/20210825/2...,L,L0
4,28,0,레이어드 슬리브리스 탑_일반 기장 [화이트],남자,173,71,적당함,//image.msscdn.net/images/goods_img/20210825/2...,M,M0
...,...,...,...,...,...,...,...,...,...,...
6145,4,39,스웨트 팬츠 [블랙],남자,187,86,적당함,//image.msscdn.net/images/goods_img/20190201/9...,L,L39
6146,4,39,스웨트 팬츠 [블랙],남자,192,87,적당함,//image.msscdn.net/images/goods_img/20190201/9...,L,L39
6147,4,39,스웨트 팬츠 [블랙],남자,178,78,적당함,//image.msscdn.net/images/goods_img/20190201/9...,L,L39
6148,4,39,스웨트 팬츠 [블랙],남자,178,78,적당함,//image.msscdn.net/images/goods_img/20190201/9...,L,L39
6149,4,39,스웨트 팬츠 [블랙],남자,168,60,적당함,//image.msscdn.net/images/goods_img/20190201/9...,S,S39

In [53]:
data2 = data1.drop(['c_number', 'c_name', 'link', 'size'], axis=1)
data2

      temp gender  height(cm)  weight(kg)  fit c_result
0       28     남자         173          65  적당함       M0
1       28     남자         184          80  적당함       L0
2       28     남자         172          63  적당함       S0
3       28     남자         182          78  적당함       L0
4       28     남자         173          71  적당함       M0
...    ...    ...         ...         ...  ...      ...
6145     4     남자         187          86  적당함      L39
6146     4     남자         192          87  적당함      L39
6147     4     남자         178          78  적당함      L39
6148     4     남자         178          78  적당함      L39
6149     4     남자         168          60  적당함      S39

[6150 rows x 6 columns]

In [54]:
data3 = data1.drop_duplicates(subset=['c_name', 'c_number'], keep='first')
data1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6150 entries, 0 to 6149
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   temp        6150 non-null   int64
 1   c_number    6150 non-null   int64
 2   c_name      6150 non-null   object
 3   gender      6150 non-null   object
 4   height(cm)  6150 non-null   int64
 5   weight(kg)  6150 non-null   int64
 6   fit         6150 non-null   object
 7   link        6150 non-null   object
 8   size        6150 non-null   object
 9   c_result    6150 non-null   object
dtypes: int64(4), object(6)
memory usage: 480.6+ KB

In [58]:
result_dict = {key: {'c_name': val['c_name'].tolist(), 'link': val['link'].tolist()} for key, val in data3.groupby('c_number')}
print(result_dict)

{0: {'c_name': ['레이어드 슬리브리스 탑_일반 기장 [화이트]'], 'link': ['//image.msscdn.net/images/goods_img/20210825/2086660/2086660_1_500.jpg']}, 1: {'c_name': ['빅 트위치 로고 티셔츠 그린'], 'link': ['//image.msscdn.net/images/goods_img/20210302/1820701/1820701_16812966368324_500.jpg']}, 2: {'c_name': ['Deep One Tuck Sweat Shorts [Grey]'], 'link': ['//image.msscdn.net/images/goods_img/20210428/1926048/1926048_1_500.jpg']}, 3: {'c_name': ['프릴 미니 드레스 (핑크)'], 'link': ['//image.msscdn.net/images/goods_img/20220609/2605850/2605850_1_500.jpg']}, 4: {'c_name': ['PLEATS DENIM SKIRT DEEP BLUE'], 'link': ['//image.msscdn.net/images/goods_img/20210602/1979439/1979439_3_500.jpg']}, 5: {'c_name': ['시티보이 빅오버 옥스포드 반팔 셔츠_Sky Blue'], 'link': ['//image.msscdn.net/images/goods_img/20210503/1935180/1935180_16810899633102_500.jpg']}, 6: {'c_name': ['스웨트 쇼츠_블랙'], 'link': ['//image.msscdn.net/images/goods_img/20220516/2560828/2560828_2_500.jpg']}, 7: {'c_name': ['케이블 니트 드레스 - 핑크'], 'link': ['//image.msscdn.net/images/goods_img/20220330/2457512/2457512_2_500.jpg']}, 8: {'c_name': ['유니섹스 와이드 밴딩 슬랙스 P-7 black'], 'link': ['//image.msscdn.net/images/goods_img/20190227/967320/967320_1_500.jpg']}, 9: {'c_name': ['스탠다드 스트라이프 포켓 롱슬리브_블랙 / 화이트'], 'link': ['//image.msscdn.net/images/goods_img/20180904/847182/847182_2_500.jpg']}, 10: {'c_name': ['스톤 워싱 오버핏 데님 반팔 셔츠 (BLEACH BLUE)'], 'link': ['//image.msscdn.net/images/goods_img/20230512/3293698/3293698_16838689790641_500.jpg']}, 11: {'c_name': ['썸머 더블턱 와이드 슬랙스[블랙]'], 'link': ['//image.msscdn.net/images/goods_img/20220524/2578996/2578996_16829900485497_500.jpg']}, 12: {'c_name': ['PLG 데님 점프수트(Blue)'], 'link': ['//image.msscdn.net/images/goods_img/20210813/2063625/2063625_16903432102296_500.jpg']}, 13: {'c_name': ['Boucle bear 오버핏 기모 맨투맨 티셔츠  AMM910 (NAVY)'], 'link': ['//image.msscdn.net/images/goods_img/20210819/2071212/2071212_1_500.jpg']}, 14: {'c_name': ['BUCKLE WIDE DENIM PANTS STONE LIGHTBLUE'], 'link': ['//image.msscdn.net/images/goods_img/20220411/2479983/2479983_5_500.jpg']}, 15: {'c_name': ['유니섹스 세미 와이드 밴딩 슬랙스 2PACK'], 'link': ['//image.msscdn.net/images/goods_img/20230428/3267784/3267784_16831377100559_500.jpg']}, 16: {'c_name': ['스몰 트위치 로고 에어로웜 루즈핏 후드집업 그레이'], 'link': ['//image.msscdn.net/images/goods_img/20210105/1737051/1737051_9_500.jpg']}, 17: {'c_name': ['PENON WIND SHELL - BLACK'], 'link': ['//image.msscdn.net/images/goods_img/20220126/2329532/2329532_16762491689303_500.jpg']}, 18: {'c_name': ['버프워시 버핑레더 인시전 바이커 자켓_Washing Black&Ivory'], 'link': ['//image.msscdn.net/images/goods_img/20230120/3036129/3036129_16745604936368_500.jpg']}, 19: {'c_name': ['베츠 어센틱 후드 그레이'], 'link': ['//image.msscdn.net/images/goods_img/20200924/1622019/1622019_6_500.jpg']}, 20: {'c_name': ['와이드 데님 팬츠 (DEEP GREY)'], 'link': ['//image.msscdn.net/images/goods_img/20181025/890338/890338_8_500.jpg']}, 21: {'c_name': ['투턱 코듀로이 벌룬 백 밴딩 팬츠 (BLACK)'], 'link': ['//image.msscdn.net/images/goods_img/20220914/2789088/2789088_1_500.jpg']}, 22: {'c_name': ['오버핏 크롭 카라 가디건 [블랙]'], 'link': ['//image.msscdn.net/images/goods_img/20211230/2286964/2286964_16781724680547_500.jpg']}, 23: {'c_name': ['피치스킨 트윌 자켓 카멜'], 'link': ['//image.msscdn.net/images/goods_img/20170310/497055/497055_2_500.jpg']}, 24: {'c_name': ['베이식 블레이저 [차콜 그레이]'], 'link': ['//image.msscdn.net/images/goods_img/20190926/1167428/1167428_2_500.jpg']}, 25: {'c_name': ['네로 옥스포드 셔츠 스카이블루'], 'link': ['//image.msscdn.net/images/goods_img/20210809/2052980/2052980_5_500.jpg']}, 26: {'c_name': ['[기모추가] 유니섹스 세미 와이드 밴딩 슬랙스 아이보리'], 'link': ['//image.msscdn.net/images/goods_img/20200624/1495284/1495284_1_500.jpg']}, 27: {'c_name': ['피쉬테일 더플 코트_네이비'], 'link': ['//image.msscdn.net/images/goods_img/20220103/2289397/2289397_4_500.jpg']}, 28: {'c_name': ['2WAY 스냅 블루종_아이보리'], 'link': ['//image.msscdn.net/images/goods_img/20210308/1833230/1833230_1_500.jpg']}, 29: {'c_name': ['(기모) 유니섹스 세미 와이드 밴딩 슬랙스 겨울 그레이'], 'link': ['//image.msscdn.net/images/goods_img/20201209/1717388/1717388_1_500.jpg']}, 30: {'c_name': ['브러쉬 스트라이프 니트_블랙/화이트'], 'link': ['//image.msscdn.net/images/goods_img/20210913/2126198/2126198_4_500.jpg']}, 31: {'c_name': ['데크 와이드빕 퍼티그 테이퍼드 오버롤 WFT-602 블랙'], 'link': ['//image.msscdn.net/images/goods_img/20210223/1809978/1809978_2_500.jpg']}, 32: {'c_name': ['유니섹스 발마칸 더플 숏 코트 (BEIGE)'], 'link': ['//image.msscdn.net/images/goods_img/20221014/2862908/2862908_1_500.jpg']}, 33: {'c_name': ['에비에이터 B-3 무스탕 자켓 [블랙]'], 'link': ['//image.msscdn.net/images/goods_img/20200903/1582142/1582142_2_500.jpg']}, 34: {'c_name': ['덕다운 아르틱 후드 패딩_Black'], 'link': ['//image.msscdn.net/images/goods_img/20221019/2877785/2877785_1_500.jpg']}, 35: {'c_name': ['보아 집업 자켓 아이보리'], 'link': ['//image.msscdn.net/images/goods_img/20200909/1593072/1593072_3_500.jpg']}, 36: {'c_name': ['성조기 코튼 니트 네이비'], 'link': ['//image.msscdn.net/images/goods_img/20220830/2754253/2754253_2_500.jpg']}, 37: {'c_name': ['오버핏 아치 로고 스웨트 셔츠-네이비'], 'link': ['//image.msscdn.net/images/goods_img/20210830/2096933/2096933_2_500.jpg']}, 38: {'c_name': ['벌룬 퍼티그 밴딩 와이드 데님 팬츠 (RAW INDIGO)'], 'link': ['//image.msscdn.net/images/goods_img/20220907/2776429/2776429_2_500.jpg']}, 39: {'c_name': ['스웨트 팬츠 [블랙]'], 'link': ['//image.msscdn.net/images/goods_img/20190201/947201/947201_3_500.jpg']}}

In [59]:
print(result_dict[0]['link'][0])

//image.msscdn.net/images/goods_img/20210825/2086660/2086660_1_500.jpg